version: "3.9"

services: 
  db: 
    image: mysql:8.0.30
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    volumes:
      - mysql:/var/lib/mysql/
    environment:
      - MYSQL_DATABASE=vnexpress
      - MYSQL_PASSWORD=deathless
      - MYSQL_ROOT_PASSWORD=deathless
      - MYSQL_HOST=db
      - MYSQL_USER=root1
    healthcheck:
      test: mysql vnexpress --user=root1 --password=deathless --silent --execute "show databases;"
      interval: 10s
      timeout: 10s
      retries: 5
  
  # redis:
  #   image: "redis:alpine"
  #   ports:
  #     - "${REDIS_HOST_PORT}:6379"
  #   environment:
  #     - REDIS_PASSWORD=${REDIS_PASSWORD}
  
  # celery:
  #   build: .
  #   command: celery -A djangoscraper.celery worker -l INFO
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     django:
  #       condition: service_started
  #     redis:
  #       condition: service_started

  # migrate:
  #   build: .
  #   command: python3 manage.py migrate --noinput
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db
  
  django:
    build: .
    container_name: django
    command: python3 manage.py runserver
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - MYSQL_DATABASE=vnexpress
      - MYSQL_PASSWORD=deathless
      - MYSQL_ROOT_PASSWORD=deathless
      - MYSQL_USER=root1
    depends_on:
      # - db
      # - migrate
      db:
        condition: service_healthy

volumes:
  mysql: 