version: "3.9"

services: 
  db: 
    image: mysql:8.0.30
    ports:
      - ${MYSQL_HOST_PORT}:3306
    volumes:
      - mysql:/var/lib/mysql/
    environment:
      - MYSQL_DB_NAME=vnexpress
      - MYSQL_DB_PASSWORD=deathless
      - MYSQL_ROOT_PASSWORD=deathless
      - MYSQL_DATABASE=vnexpress
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_DB_PASSWORD}"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 5
  
  # redis:
  #   image: "redis:alpine"
  #   ports:
  #     - "${REDIS_HOST_PORT}:6379"
  #   environment:
  #     - REDIS_PASSWORD=${REDIS_PASSWORD}
  
  # celery:
  #   build: .
  #   command: celery -A djangoscraper.celery worker -l INFO
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     django:
  #       condition: service_started
  #     redis:
  #       condition: service_started
  
  django:
    build: .
    container_name: django
    command: python3 manage.py runserver
    ports:
      - ${DJANGO_HOST_PORT}:8000
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - MYSQL_NAME=vnexpress
      - MYSQL_PASSWORD=deathless
      - MYSQL_ROOT_PASSWORD=deathless
    depends_on:
      - db
      # db:
      #   condition: service_healthy

volumes:
  mysql: 