version: "3.9"

services: 
  db: 
    image: mysql:8.0.30
    ports:
      - 3307:3306
    volumes:
      - mysql:/var/lib/mysql/
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
    healthcheck:
      test: mysql ${MYSQL_DATABASE} --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} --silent --execute "show databases;"
      interval: 10s
      timeout: 10s
      retries: 5
  
  redis:
    image: "redis:alpine"
    ports:
      - "${REDIS_HOST_PORT}:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
  
  celery:
    build: .
    command: celery -A djangoscraper.celery worker -l INFO
    volumes:
      - .:/app
    depends_on:
      django:
        condition: service_started
      redis:
        condition: service_started

  # migrate:
  #   build: .
  #   command: python3 manage.py migrate --noinput
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db
  
  django:
    build: .
    container_name: django
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - ${DJANGO_HOST_PORT}:8000
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    tty: true

volumes:
  mysql: 