# Generated by Django 4.0.5 on 2022-07-28 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokenblacklist',
            old_name='uid',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='tokenblacklist',
            name='token',
        ),
        migrations.AddField(
            model_name='tokenblacklist',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
