# Generated by Django 4.0.5 on 2022-09-14 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0002_remove_tokenblacklist_user_tokenblacklist_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokenblacklist',
            old_name='user_id',
            new_name='user',
        ),
    ]
