# Generated by Django 4.0.5 on 2022-06-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsscraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
