# Generated by Django 4.0.5 on 2022-08-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articlescraper', '0002_news_create_at_news_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
